#! python3
# Программа для перевода данных таблиц ТЗА-1 в удобный для работы вид
"""
Общий план:
1. Получение данных из файла
2. Распознование отдельных элементов таблицы (номер поста, год, месяц, дата,
срок, метеовеличины,концентрации примесей)
3. Вывод обработанных результатов в удобном для дальнейшей обрабоки формате
"""

import re # импорт модуля для работы с регулярными выражениями
import pyperclip # импорт модуля для работы с буфером обмена
import os # импорт модуля для работы с файлами и путями

def postNumberFind(data):
    #Функция принимает исходный текст и возвращает номер поста наблюдения
    postNumberRegex = re.compile(r'Пост\s*(\d)')
    mo = postNumberRegex.search(data)
    postNumber = mo.group(1)

    return postNumber

def yearFind(data):
    #Функция принимает исходный текст и возвращает год наблюдения
    yearRegex = re.compile(r'год\s*(\d\d\d\d)')
    mo = yearRegex.search(data)
    year = mo.group(1)

    return year

def monthFind(data):
    #Функция принимает исходный текст и возвращает месяц наблюдения
    monthRegex = re.compile(r'месяц\s*(\d\d)')
    mo = monthRegex.search(data)
    month = mo.group(1)

    return month

def observationaldataFind(data):
    '''Функция принимает исходный текст и список дат, сроков, метеоданных
    концентраций веществ найденных регулярным выражением'''
    observationaldataRegex = re.compile(r'''
    (│|¦)           # разделитель
    (\s?\d+)        # дата
    (│|¦)           # разделитель
    (\s?\d+)        # срок
    (│|¦)           # разделитель
    (-*\s*\d+\.\d)  # температура, оС
    (│|¦)           # разделитель
    (\s?\d+\s?)     # направление ветра гр*10
    (│|¦)           # разделитель
    (\s?\d+\s?)     # скорость ветра м/с
    (│|¦)           # разделитель
    (\d)            # атм. явления
    (│|¦)           # разделитель
    (\s*\d+)        # относительная влажность, %
    (│|¦)           # разделитель
    (\s*\d*)        # упругость водяного пара, гПа
    (│|¦)           # разделитель
    (\s*\d+)        # взвешенные веществ *10^-1
    (│|¦)           # разделитель
    (\s*\d+)        # диоксид серы SO2 *10^-3
    (│|¦)           # разделитель
    (\s*\d+)        # оксид углерода CO *10^0
    (│|¦)           # разделитель
    (\s*\d+)        # диоксид азота NO2 *10^-2
    (│|¦)           # разделитель
    (\s*\d+)        # оксид азота NO *10^-3
    (│|¦)           # разделитель
    (\s*\d+)        # формальдегид CH2O *10^-3
    ''',re.X)
    observationaldata = observationaldataRegex.findall(data)

    return observationaldata
    
def dataByObservation(data, year, month, post):
    '''Функция принимает список с наблюдениями по срокам, год, месяц
    и номер поста наблюдения и возвращает отформатированный текст со
    значениями разделенными точкой с запятой'''
    fulltxt = ''
    for i in data:
        # создается список содержащий необходимые части объектов совпадения
        # регулярных выражений
        txtlist = [post, year, month, i[1], i[3], i[5], i[7], i[9], i[11],
                   i[13], i[15], i[17], i[19], i[21], i[23], i[25], i[27]]
        txt = ''
        for j in txtlist:
            # создается строка с данными по каждому строку
            txt = txt + str(j)+';'
        fulltxt = fulltxt + txt + '\n'
        #строки объединяются в один большой текст

    return fulltxt
        
def fileReading(filePath):
    '''Функция извлекает из файла filePath исходные данные и возвращает их
    в виде текста'''
    file = open(filePath)
    fileForRegex = file.readlines()
    data = str(fileForRegex)
    file.close()

    return data

def writeFile(data):
    '''Функция создает файл и записывает в него преобразованные данные'''
    tzaResult = open('tzaResult.txt', 'w')    
    tzaResult.write(data)
    tzaResult.close()

def fileExistenceCheck():
    '''Функция проверяет существование файла с исходными данными'''
    filePath = os.path.join(os.getcwd(), 'tza.txt')
    if os.path.exists(filePath):
        return filePath
    else:
        print('Файл не найден. Проверьте присутствуют ли в папке' +
                  ' с программой файл tza.txt' +
              '\n(Возможно он удален или переименован)')
        print('Для продолжения нажмите клавишу \'ENTER\'')
        pause = input()

def converting():
    '''Функция производит все необходимые действия если существует filePath'''
    if filePath:
        initialData = fileReading(filePath)
        post = (postNumberFind(initialData))
        year = (yearFind(initialData))
        month = (monthFind(initialData))
        foundData = observationaldataFind(initialData)
        outputData = dataByObservation(foundData, year, month, post)
        writeFile(outputData)

filePath = fileExistenceCheck()
converting()

#TODO: сделать возможность чтения нескольких файлов
#TODO: сделать возможность дополнение, а не перезаписи выходного файла
#TODO: селать чтение из исходного файла .bat

