#! python3
# Программа для перевода данных таблиц ТЗА-1 в удобный для работы вид
"""
Общий план:
1. Получение данных из файла
2. Распознование отдельных элементов таблицы (номер поста, год, месяц, дата,
срок, метеовеличины,концентрации примесей)
3. Вывод обработанных результатов в удобном для дальнейшей обрабоки формате
"""

import re # импорт модуля для работы с регулярными выражениями
import pyperclip # импорт модуля для работы с буфером обмена

def postNumberFind(data):
    #Функция принимает исходный текст и возвращает номер поста наблюдения
    postNumberRegex = re.compile(r'Пост\s*\d')
    mo = postNumberRegex.search(data)
    postNumber = mo.group()

    return postNumber

def yearFind(data):
    #Функция принимает исходный текст и возвращает год наблюдения
    yearRegex = re.compile(r'год\s*\d\d\d\d')
    mo = yearRegex.search(data)
    year = mo.group()

    return year

def monthFind(data):
    #Функция принимает исходный текст и возвращает месяц наблюдения
    monthRegex = re.compile(r'месяц\s*\d\d')
    mo = monthRegex.search(data)
    month = mo.group()

    return month

#TODO регулярное выражение для строки типа:
# │ 1│ 7│  8.0│23 │ 3 │4│  91│    │    1│    0│    1│   17│    8│    3│
# с вычленением даты, срока, метеовеличин и концентраций примесей
# использовать большое регулярное выражение содержащее несколько групп
# см. AverageMeteo

#TODO регулярные выражения для всех элементов таблицы



data = str(pyperclip.paste()) # Программа принимает данные из буфера обмена

print(postNumberFind(data))
print(yearFind(data))
print(monthFind(data))



